// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqzsifwfqmviizfevhdw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxenNpZndmcW12aWl6ZmV2aGR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDM2OTgsImV4cCI6MjA2NDUxOTY5OH0.0QImUDRzzkwhb8bTByZmmkBdDzDwSVEmZskEvteuJ2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);